# Generated by Django 2.0 on 2020-07-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phoneno', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productbrand', models.CharField(default='', max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('published_on', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images1/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images1/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images1/')),
                ('description', models.TextField(default='')),
                ('material', models.CharField(default='', max_length=500)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('discounted_price', models.IntegerField(default=0)),
                ('size', models.CharField(default='', max_length=500)),
                ('Type', models.CharField(default='', max_length=500)),
                ('Occasion', models.CharField(default='', max_length=500)),
                ('pattern', models.CharField(default='', max_length=500)),
                ('color', models.CharField(default='', max_length=500)),
                ('Features', models.CharField(default='', max_length=500)),
                ('productcode', models.CharField(default='', max_length=500)),
                ('availabily', models.CharField(blank=True, choices=[('STOCK', 'In Stock'), ('OUT OF STOCK', 'Out Of Stock')], max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('tag', models.CharField(choices=[('new', 'NEW'), ('stylish', 'STYLISH'), ('trending', 'TRENDING'), ('beautiful', 'BEAUTIFUL'), ('awesome', 'AWESOME'), ('popular', 'POPULAR'), ('swank', 'SWANK'), ('cool', 'COOL'), ('fashionable', 'FASHIONABLE'), ('snazzy', 'SNAZZY'), ('exculsive', 'EXCLUSIVE'), ('dashing', 'DASHING')], max_length=20)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'query',
            },
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='fabtrendapp.category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabtrendapp.subcategory'),
        ),
    ]
